### ISSUE TITLE
Remove Tracuer dependecy

### ISSUE THREAD

**Issue by EaterOfCode** [jcfrancisco/snaps#4]
Currently I get this error (Im sorry Im using windows atm :( )

C:\Users\coppelaar\Documents\snapdownload\node_modules\snaps\lib\snaps.js:10
    bqLogin = $traceurRuntime.assertObject(require('./endpoints/bq_login')).bq
                              ^
TypeError: Object #<Object> has no method 'assertObject'
    at Object.<anonymous> (C:\Users\coppelaar\Documents\snapdownload\node_module
s\snaps\lib\snaps.js:10:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\coppelaar\Documents\snapdownload\index.js:2:
13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by jcfrancisco** [comment]
Hey!

Could you link to a repo or gist where this code can be found? I can pull it down to my Windows machine and try out a few things.

**Comment by EaterOfCode** [comment]
Sorry for the weird  wording, been playing with it ever since. tracuer is probably the problem but as far as I've seen its an compiler so Im not really sure what is happening

basically, I did `npm i snaps`

did `require('snaps')`

and it dies :(

**Comment by EaterOfCode** [comment]
I can confirm on Ubuntu too

**Comment by EaterOfCode** [comment]
after I installed it via git and ran `npm run prepublish` in the snaps folder it seems fine : D

**Comment by jcfrancisco** [comment]
hey @EaterOfCode 

I just published a new version (v0.1.1). Can you pull it down and see whether you can get it to work without running `npm run prepublish`?

**Comment by jcfrancisco** [comment]
I think I figured out the issue. It should be fixed in v0.1.2.
